name: Check number of changed files
on: pull_request

permissions:
  actions: write

jobs:
  check_number_of_changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Get changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            src/**/*.{js,jsx,ts,tsx,json}
            .github/workflows/**

      - name: Check number of changed files
        run: |
          echo "Number of changed files: ${{ steps.get_changed_files.outputs.all_changed_files_count }}"
          if [ ${{ steps.get_changed_files.outputs.all_changed_files_count }} -gt 15 ]; then
            echo "Too many changed files. Please limit your PR to 15 files or less."
            exit 1
          fi
