name: Lint Code in Pushes and PRs
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Lint code
        run: yarn run lint

      - name: Lint commit message
        run: yarn run npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
